---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse
- name: Install Vector
  hosts: vector
  roles: 
    - vector-role 
- name: install Nginx Web server 
  hosts: lighthouse
  roles:
    - lighthouse-role
- name: Install lighthouse
  hosts: lighthouse-01
  roles:
    - lighthouse-role
